<?php

/**
 * @file
 *   Views dev.
 */

/**
 * Implementation of hook_views_api().
 */
function voipviews_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'voipviews') . '/views',
  );
}

/**
 * Implementation of hook_theme().
 */
function voipviews_theme($existing, $type, $theme, $path) {
  return array(
    'voipviews_view_preview' => array(
      'arguments' => array(
        'voipscriptstore' => '',
      ),
      'file' => 'theme/voipviews.theme.inc',
    ),
  );
}

/**
 * Impelementation of hook_menu().
 */
function voipviews_menu() {
  // we can check for new, changed, extension on form submission, but not programatically
  // similarly on deleting there is nothing in $view->delete (just form submission if from ui)
  // a menu rebuild is however always triggered, so updating our extensions here
  voipviews_refresh_extensions();
}

/**
 * Add, update and remove voip views extensions.
 */
function voipviews_refresh_extensions() {
  if (! module_exists('voipextension')) {
    return;
  }

  $extensions = voipextension_load_module_extensions('voipviews');

  // cycle through all voip views displays
  $views = views_get_applicable_views('uses voipextension');
  foreach ($views as $data) {
    list($view, $display_id) = $data;
    $view->set_display($display_id);
    // if the voipextension checkbox is enabled
    if ($view->display_handler->get_option('voipextension_enable')) {
      // check to see if it exists already
      if (isset($extensions[$view->name . '|' . $display_id])) {
        $extension = $extensions[$view->name . '|' . $display_id];
        $extension['title'] = $view->display_handler->get_option('voipextension_title');
        $extension['description'] = $view->display_handler->get_option('voipextension_description');
        $extension['script_callback'] = 'voipviews_voipextension_script_callback';
        voipextension_update($extension);
        unset($extensions[$view->name . '|' . $display_id]);
      }
      else {
        // otherwise create new extension
        $extension = array(
          'title' => $view->display_handler->get_option('voipextension_title'),
          'description' =>  $view->display_handler->get_option('voipextension_description'),
          'module' => 'voipviews',
          'module_id' => $view->name . '|' . $display_id,
          'script_callback' => 'voipviews_voipextension_script_callback',
        );
        voipextension_create($extension);
      }
    }
  }

  // remove any extensions that are remaining they are deleted or disabled.
  foreach($extensions as $module_id => $extension) {
    voipextension_delete($extension['eid']);
  }

  // Save memory: Destroy those views.
  foreach ($views as $data) {
    list($view, $display_id) = $data;
    $view->destroy();
  }
}

/**
 * Voipextension script callback.
 */
function voipviews_voipextension_script_callback(&$extension) {
  list($view_name, $display_id) = explode('|', $extension['module_id']);
  $extension['script_arguments']['view_name'] = $view_name;
  $extension['script_arguments']['display_id'] = $display_id;
  return 'voipviews_read_view';
}

/**
 * Implementation of hook_voipscript_get_script_names().
 */
function voipviews_voipscript_get_script_names() {
  return array(
    'voipviews_read_view',
  );
}

/**
 * Implementation of hook_voipscript_load_script().
 */
function voipviews_voipscript_load_script($script_name, $params = NULL) {
  switch ($script_name) {
    case 'voipviews_read_view':
      $args = (! empty($params['args'])) ? json_decode($params['args']) : array();
      return voipviews_read_view_script($params['view_name'], $params['display_id'], $args);
  }
} 

/**
 * Return a script from a view display.
 */
function voipviews_read_view_script($view_name, $display_id, $args = array()) {
  $view = views_get_view($view_name);
  if (!$view || !$view->access($display_id)) {
   $script = new VoipScript('voipviews_script_view_read');
   $script->addSay('There has been an error accessing the information you require. Sorry.');
   $script->addReturn();
   return $script;
  }
  if (! $view->set_display($display_id)) {
   $script = new VoipScript('voipviews_script_view_read');
   $script->addSay('There has been an error accessing the information you require. Sorry.');
   $script->addReturn();
   return $script;
  }

  if (! empty($options['filters'])) {
    $view->set_exposed_input($options['filters']);
  }

  $view->pre_execute($args);
  $stored_script = $view->display_handler->preview();
  $view->post_execute();

  // @todo put this in the store class.
  $script = new VoipScript($stored_script->getName(), $stored_script->getVariables());
  foreach ($stored_script as $line) {
    list($command, $params) = $line;
    call_user_func_array(array($script, $command), $params);
  }

  return $script;
}
